/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SolicitudReclutamiento service. Represents a row in the &quot;SolicitudReclutamiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rec.hitss.service.model.impl.SolicitudReclutamientoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rec.hitss.service.model.impl.SolicitudReclutamientoImpl}.
 * </p>
 *
 * @author Danielle
 * @see SolicitudReclutamiento
 * @see com.rec.hitss.service.model.impl.SolicitudReclutamientoImpl
 * @see com.rec.hitss.service.model.impl.SolicitudReclutamientoModelImpl
 * @generated
 */
public interface SolicitudReclutamientoModel extends BaseModel<SolicitudReclutamiento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitud reclutamiento model instance should use the {@link SolicitudReclutamiento} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitud reclutamiento.
	 *
	 * @return the primary key of this solicitud reclutamiento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this solicitud reclutamiento.
	 *
	 * @param primaryKey the primary key of this solicitud reclutamiento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the solicitud reclutamiento ID of this solicitud reclutamiento.
	 *
	 * @return the solicitud reclutamiento ID of this solicitud reclutamiento
	 */
	public long getSolicitudReclutamientoId();

	/**
	 * Sets the solicitud reclutamiento ID of this solicitud reclutamiento.
	 *
	 * @param solicitudReclutamientoId the solicitud reclutamiento ID of this solicitud reclutamiento
	 */
	public void setSolicitudReclutamientoId(long solicitudReclutamientoId);

	/**
	 * Returns the puesto of this solicitud reclutamiento.
	 *
	 * @return the puesto of this solicitud reclutamiento
	 */
	@AutoEscape
	public String getPuesto();

	/**
	 * Sets the puesto of this solicitud reclutamiento.
	 *
	 * @param puesto the puesto of this solicitud reclutamiento
	 */
	public void setPuesto(String puesto);

	/**
	 * Returns the user name create of this solicitud reclutamiento.
	 *
	 * @return the user name create of this solicitud reclutamiento
	 */
	@AutoEscape
	public String getUserNameCreate();

	/**
	 * Sets the user name create of this solicitud reclutamiento.
	 *
	 * @param userNameCreate the user name create of this solicitud reclutamiento
	 */
	public void setUserNameCreate(String userNameCreate);

	/**
	 * Returns the create date of this solicitud reclutamiento.
	 *
	 * @return the create date of this solicitud reclutamiento
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this solicitud reclutamiento.
	 *
	 * @param createDate the create date of this solicitud reclutamiento
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the user name update of this solicitud reclutamiento.
	 *
	 * @return the user name update of this solicitud reclutamiento
	 */
	@AutoEscape
	public String getUserNameUpdate();

	/**
	 * Sets the user name update of this solicitud reclutamiento.
	 *
	 * @param userNameUpdate the user name update of this solicitud reclutamiento
	 */
	public void setUserNameUpdate(String userNameUpdate);

	/**
	 * Returns the modified date of this solicitud reclutamiento.
	 *
	 * @return the modified date of this solicitud reclutamiento
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this solicitud reclutamiento.
	 *
	 * @param modifiedDate the modified date of this solicitud reclutamiento
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SolicitudReclutamiento solicitudReclutamiento);

	public int hashCode();

	public CacheModel<SolicitudReclutamiento> toCacheModel();

	public SolicitudReclutamiento toEscapedModel();

	public String toString();

	public String toXmlString();
}