/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rec.hitss.service.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rec.hitss.service.model.SolicitudReclutamiento;
import com.rec.hitss.service.model.SolicitudReclutamientoModel;
import com.rec.hitss.service.model.SolicitudReclutamientoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SolicitudReclutamiento service. Represents a row in the &quot;SolicitudReclutamiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rec.hitss.service.model.SolicitudReclutamientoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SolicitudReclutamientoImpl}.
 * </p>
 *
 * @author Danielle
 * @see SolicitudReclutamientoImpl
 * @see com.rec.hitss.service.model.SolicitudReclutamiento
 * @see com.rec.hitss.service.model.SolicitudReclutamientoModel
 * @generated
 */
@JSON(strict = true)
public class SolicitudReclutamientoModelImpl extends BaseModelImpl<SolicitudReclutamiento>
	implements SolicitudReclutamientoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitud reclutamiento model instance should use the {@link com.rec.hitss.service.model.SolicitudReclutamiento} interface instead.
	 */
	public static final String TABLE_NAME = "SolicitudReclutamiento";
	public static final Object[][] TABLE_COLUMNS = {
			{ "solicitudReclutamientoId", Types.BIGINT },
			{ "puesto", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SolicitudReclutamiento (solicitudReclutamientoId LONG not null primary key,puesto VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SolicitudReclutamiento";
	public static final String ORDER_BY_JPQL = " ORDER BY solicitudReclutamiento.puesto ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SolicitudReclutamiento.puesto ASC";
	public static final String DATA_SOURCE = "recportalDataSource";
	public static final String SESSION_FACTORY = "recportalSessionFactory";
	public static final String TX_MANAGER = "recportalTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rec.hitss.service.model.SolicitudReclutamiento"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rec.hitss.service.model.SolicitudReclutamiento"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rec.hitss.service.model.SolicitudReclutamiento"),
			true);
	public static long PUESTO_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SolicitudReclutamiento toModel(
		SolicitudReclutamientoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SolicitudReclutamiento model = new SolicitudReclutamientoImpl();

		model.setSolicitudReclutamientoId(soapModel.getSolicitudReclutamientoId());
		model.setPuesto(soapModel.getPuesto());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SolicitudReclutamiento> toModels(
		SolicitudReclutamientoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SolicitudReclutamiento> models = new ArrayList<SolicitudReclutamiento>(soapModels.length);

		for (SolicitudReclutamientoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rec.hitss.service.model.SolicitudReclutamiento"));

	public SolicitudReclutamientoModelImpl() {
	}

	public long getPrimaryKey() {
		return _solicitudReclutamientoId;
	}

	public void setPrimaryKey(long primaryKey) {
		setSolicitudReclutamientoId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_solicitudReclutamientoId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SolicitudReclutamiento.class;
	}

	public String getModelClassName() {
		return SolicitudReclutamiento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("solicitudReclutamientoId", getSolicitudReclutamientoId());
		attributes.put("puesto", getPuesto());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long solicitudReclutamientoId = (Long)attributes.get(
				"solicitudReclutamientoId");

		if (solicitudReclutamientoId != null) {
			setSolicitudReclutamientoId(solicitudReclutamientoId);
		}

		String puesto = (String)attributes.get("puesto");

		if (puesto != null) {
			setPuesto(puesto);
		}
	}

	@JSON
	public long getSolicitudReclutamientoId() {
		return _solicitudReclutamientoId;
	}

	public void setSolicitudReclutamientoId(long solicitudReclutamientoId) {
		_solicitudReclutamientoId = solicitudReclutamientoId;
	}

	@JSON
	public String getPuesto() {
		if (_puesto == null) {
			return StringPool.BLANK;
		}
		else {
			return _puesto;
		}
	}

	public void setPuesto(String puesto) {
		_columnBitmask = -1L;

		if (_originalPuesto == null) {
			_originalPuesto = _puesto;
		}

		_puesto = puesto;
	}

	public String getOriginalPuesto() {
		return GetterUtil.getString(_originalPuesto);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SolicitudReclutamiento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SolicitudReclutamiento toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (SolicitudReclutamiento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SolicitudReclutamientoImpl solicitudReclutamientoImpl = new SolicitudReclutamientoImpl();

		solicitudReclutamientoImpl.setSolicitudReclutamientoId(getSolicitudReclutamientoId());
		solicitudReclutamientoImpl.setPuesto(getPuesto());

		solicitudReclutamientoImpl.resetOriginalValues();

		return solicitudReclutamientoImpl;
	}

	public int compareTo(SolicitudReclutamiento solicitudReclutamiento) {
		int value = 0;

		value = getPuesto().compareTo(solicitudReclutamiento.getPuesto());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SolicitudReclutamiento solicitudReclutamiento = null;

		try {
			solicitudReclutamiento = (SolicitudReclutamiento)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = solicitudReclutamiento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SolicitudReclutamientoModelImpl solicitudReclutamientoModelImpl = this;

		solicitudReclutamientoModelImpl._originalPuesto = solicitudReclutamientoModelImpl._puesto;

		solicitudReclutamientoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SolicitudReclutamiento> toCacheModel() {
		SolicitudReclutamientoCacheModel solicitudReclutamientoCacheModel = new SolicitudReclutamientoCacheModel();

		solicitudReclutamientoCacheModel.solicitudReclutamientoId = getSolicitudReclutamientoId();

		solicitudReclutamientoCacheModel.puesto = getPuesto();

		String puesto = solicitudReclutamientoCacheModel.puesto;

		if ((puesto != null) && (puesto.length() == 0)) {
			solicitudReclutamientoCacheModel.puesto = null;
		}

		return solicitudReclutamientoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{solicitudReclutamientoId=");
		sb.append(getSolicitudReclutamientoId());
		sb.append(", puesto=");
		sb.append(getPuesto());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.rec.hitss.service.model.SolicitudReclutamiento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>solicitudReclutamientoId</column-name><column-value><![CDATA[");
		sb.append(getSolicitudReclutamientoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>puesto</column-name><column-value><![CDATA[");
		sb.append(getPuesto());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SolicitudReclutamiento.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			SolicitudReclutamiento.class
		};
	private long _solicitudReclutamientoId;
	private String _puesto;
	private String _originalPuesto;
	private long _columnBitmask;
	private SolicitudReclutamiento _escapedModelProxy;
}